spring:
  application:
    name: user-management-graphql  # Name of the application, used for identification in logs and other configurations.

  datasource:
    url: jdbc:postgresql://${IP_DATABASE:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}  # Connection URL for PostgreSQL database, using environment variables for IP, port, and database name.
    username: ${POSTGRES_USER:postgres}  # Username for connecting to the database, with a default value 'postgres'.
    password: ${POSTGRES_PASSWORD:1q2w3e4r}  # Password for connecting to the database, with a default value '1q2w3e4r'.

  graphql:
    graphiql:
      enabled: true  # Enables the GraphiQL interface for exploring and testing the GraphQL API.
      path: /graphiql  # Path where GraphiQL will be accessible.

  jpa:
    hibernate:
      ddl-auto: none  # Database schema generation strategy; 'none' means no automatic changes will be made.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Hibernate dialect for PostgreSQL, optimizes the generated SQL queries.

logging:
  level:
    org:
      hibernate:
        SQL: debug  # Logging level for SQL queries generated by Hibernate, 'debug' shows the queries in the logs.

server:
  port: 8080  # Port where the Spring Boot application server will listen for requests.